### ISSUE TITLE
Feature request: accept the text of the current line as a parameter

### ISSUE THREAD

**Issue by ryanjamurphy** [kzhovn/uri-commands-obsidian#1]
It would be great to add the current line as an accepted parameter. Especially useful for sharing e.g., tasks to other apps and services.

PS: Very happy this exists. I can now take a similar idea off of my plugins-to-build list. Great work!

**Comment by kzhovn** [comment]
Done in [0.4.0](https://github.com/kzhovn/uri-commands-obsidian/releases/tag/0.4.0).
