### ISSUE TITLE
Hotkey assignments lost if a command is edited

### ISSUE THREAD

**Issue by pjeby** [kzhovn/uri-commands-obsidian#3]
The code in URIModal sets a new ID for a command each time it's edited, instead of only assigning an ID once, when the command is first created.  This causes hotkey assignments to be lost, because Obsidian stores them by command ID.  So every time you edit a command, you have to go back and re-assign a hotkey to it, and the old hotkey assignments will accumulate in Obsidian's hotkeys.json.

The fix would be to move the ID assignment into the `if` branch for creating a new command, so that once it is created, a command will always have the same ID.

**Comment by kzhovn** [comment]
Fixed in [0.4.3](https://github.com/kzhovn/uri-commands-obsidian/releases/tag/0.4.3).
