### ISSUE TITLE
Suggestion: display notice of URL being opened

### ISSUE THREAD

**Issue by pjeby** [kzhovn/uri-commands-obsidian#4]
Before I realized #3 was an issue, I kept hitting a hotkey over and over and nothing was happening and couldn't tell whether it was Obsidian or Calibre.  I ended up adding a `new Notice(`Opening ${URIString}`);` line before each `window.open()` so that I could see exactly what URL was being launched, which was helpful both for finding a problem with my configuration, and for getting active feedback that the command was being invoked at all.

I suspect other people might find this useful as well.

(Though perhaps a more robust version that cuts off the URL after it gets to a certain length would be best, since fileText insertions could make for some huge notices!)

**Comment by kzhovn** [comment]
Done (as a setting) in [0.4.3](https://github.com/kzhovn/uri-commands-obsidian/releases/tag/0.4.3).

Currently doesn't cut off the URI because it's cut off by Obsidian past a certain length, but if this notification is still too large I can fix that.
