### ISSUE TITLE
Disabling notice when executing command

### ISSUE THREAD

**Issue by imed-ghomari** [kzhovn/uri-commands-obsidian#6]
A setting to disable the notice that appears whenever a command is executed would be nice, thank you.

**Comment by imed-ghomari** [comment]
By using advanced URI plugin, there is no notice appearing, so I'm clothing this.

**Comment by kzhovn** [comment]
Reopening, this should be an easy toggle to add and I expect other users might want it as well.

**Comment by kzhovn** [comment]
Already implemented and forgot about it, apparently. Closing.
