### ISSUE TITLE
[Feature Request] Add path (in vault) to placeholder

### ISSUE THREAD

**Issue by AndyLiu9** [kzhovn/uri-commands-obsidian#7]
Thanks for your plugin! Is there any possibility to add the current file path (I mean relative path in the vault) to placeholder?

**Comment by AndyLiu9** [comment]
(And one more FR: add vault name to placeholder)

**Comment by kzhovn** [comment]
Done, let me know if there are any issues!

**Comment by AndyLiu9** [comment]
Thanks for your quick response! Seems that I can’t update the plug-in in my community plug-in list. The latest version is still 0.4.4 but the description page has been updated. (Maybe it’s  a github issue or Obsidian issue)
Could you please help to take a look at your Obsidian community plug-in list?
![8AFA032E-FBB8-4C47-BF28-5D9A06B2D49E](https://user-images.githubusercontent.com/88693956/167670781-b24098e0-87f7-4d32-8a2a-aba54fe5b53a.jpeg)

**Comment by kzhovn** [comment]
Forgot to push a version bump, oops. Should be fixed now.

**Comment by AndyLiu9** [comment]
Amazing! Thanks for your help!
